### ISSUE TITLE
持续集成

### ISSUE THREAD

**Issue by brt2cv** [dongfanger/pycnblog#1]
很棒的脚本~
不过对于上传过的md，如果二次编辑以后（不修改标题），再次执行上传，是否会造成冲突？该如何解决。
实际上，我是直接上传整个目录。希望能够自动更新文章，是否可行？

**Comment by dongfanger** [comment]
已经可以二次编辑了哦。
如果上传的md已经存在，会提示“博客已存在, 是否更新?(y/n)”，输入"y"就可以更新了。

**Comment by dongfanger** [comment]
> 很棒的脚本~
> 不过对于上传过的md，如果二次编辑以后（不修改标题），再次执行上传，是否会造成冲突？该如何解决。
> 实际上，我是直接上传整个目录。希望能够自动更新文章，是否可行？
已经可以二次编辑了哦。
如果上传的md已经存在，会提示“博客已存在, 是否更新?(y/n)”，输入"y"就可以更新了。

**Comment by dongfanger** [comment]
已经可以二次编辑了哦。 如果上传的md已经存在，会提示“博客已存在, 是否更新?(y/n)”，输入"y"就可以更新了。
