### ISSUE TITLE
运行没有反应

### ISSUE THREAD

**Issue by jia-wink** [dongfanger/pycnblog#13]
![image](https://user-images.githubusercontent.com/96378404/161370027-a0b9fe16-ec1c-43bb-b5fe-f3eb979f3079.png)
配置好之后双击运行拖拽文件进去之后按回车没有反应，如果是以管理员身份运行则根本拖拽不进去

**Comment by dongfanger** [comment]
python upload.py %filePath% 试一下看报啥错呢
