### ISSUE TITLE
未生成新文件，未发布的的博客也不能正常显示

### ISSUE THREAD

**Issue by shui888888** [dongfanger/pycnblog#18]
![1](https://user-images.githubusercontent.com/88701700/192691097-3bf89b64-3fa4-4968-b968-d404d022126c.png)
![2](https://user-images.githubusercontent.com/88701700/192691109-6caa1e7c-7d27-4036-b0df-b837bd7e7503.png)

**Comment by dongfanger** [comment]
从截图来看，不是已经成功了吗
