### ISSUE TITLE
Mac 版本工具

### ISSUE THREAD

**Issue by wangbs95** [dongfanger/pycnblog#4]
请问是否可以封装一个 Mac 版本的工具出来，我是golang 语言，自己搞有点够呛

**Comment by dongfanger** [comment]
> 请问是否可以封装一个 Mac 版本的工具出来，我是golang 语言，自己搞有点够呛

已经添加啦，请看README下方mac部分内容。

**Comment by wangbs95** [comment]
![WeChat08a2b2022751542c19ed523014aca87b.png](https://i.loli.net/2020/11/11/m6ua1bBeEVvjZKI.png)

如图，在非命令所在目录执行会报错
