### ISSUE TITLE
mac非命令所在目录执行报错

### ISSUE THREAD

**Issue by wangbs95** [dongfanger/pycnblog#5]
![](https://i.loli.net/2020/11/17/NgE8avc9CkFZtYi.png)

https://i.loli.net/2020/11/17/NgE8avc9CkFZtYi.png

如上图，在非~/PycharmProjects/pycnblog目录执行会报错，应该是程序 base 路径问题

**Comment by dongfanger** [comment]
修改cnblogmd文件
python3 /tool_local_path/upload.py
