### ISSUE TITLE
更新文章 tag 消失

### ISSUE THREAD

**Issue by wangbs95** [dongfanger/pycnblog#6]
https://i.loli.net/2020/11/17/UeHVbE1TrCFplQ9.png

发布文章后，在文章编辑界面会为文章添加 tag 以作分类，但是使用工具更新文章后 tag 属性消失，希望作者做出修复，并且如摘要图片等文章属性请都考虑一下，谢谢

**Comment by dongfanger** [comment]
已修复。博客更新时，会保留个人分类、摘要和标签。

**Comment by wangbs95** [comment]
> 已修复。博客更新时，会保留个人分类、摘要和标签。

thx
