### ISSUE TITLE
.svg 格式图片上传报错

### ISSUE THREAD

**Issue by wangbs95** [dongfanger/pycnblog#7]
https://i.loli.net/2020/11/27/DtLpi4wSOc7gsNm.png

如图，如果 md 文档中的图片包含 .svg 格式，上传时会报错。不知道是博客园不支持此格式还是 pycnblog 工具没有考虑到此格式。

若可修复，请考虑更全面的图片格式支持。

谢谢！

**Comment by dongfanger** [comment]
试了下，不支持：
`xmlrpc.client.Fault: <Fault 500: '! only allow (\\.jpg|\\.gif|\\.png|\\.jpeg)$'>`
只能先转换下格式了。

**Comment by wangbs95** [comment]
> 试了下，不支持：
> `xmlrpc.client.Fault: <Fault 500: '! only allow (\\.jpg|\\.gif|\\.png|\\.jpeg)$'>`
> 只能先转换下格式了。

thx
