### ISSUE TITLE
文章更新失败

### ISSUE THREAD

**Issue by wangbs95** [dongfanger/pycnblog#8]
https://i.loli.net/2020/12/07/u52RvPQ9I47AJj3.png

如图，第一篇博文更新不成功，并且命令行少更新成功提示，实际博客也更新不成功。这篇文章印象里是更新成功过几回的，后来就不行了。

博客文章地址：
https://www.cnblogs.com/wangbs95/p/14080619.html

**Comment by dongfanger** [comment]
【问题原因】判断是否需要更新时，处理了HTML转义字符：
`recent_posts_titles = [html.unescape(recent_post['title']) for recent_post in recent_posts]`
但实际更新时没有处理：
`            if title ==recent_post['title']:`
【问题解决】
`            if title == html.unescape(recent_post['title']):`
我这windows重现不了，你能更新代码再试试么，应该ok了
